// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nami.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nami.API.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nami.API.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Nami.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Nami.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Platos principales del menú",
                            Name = "Platos fuertes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bebidas frías y calientes",
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Postres y dulces",
                            Name = "Postres"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hamburguesas, papas y combos",
                            Name = "Comida rápida"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ceviches y platos de mar",
                            Name = "Mariscos"
                        });
                });

            modelBuilder.Entity("Nami.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Nami.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<double>("DeliveryLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("DeliveryLongitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("DeliveryRating")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryRatingComment")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Nami.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Nami.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Nami.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Carne, huevo, plátano y arroz",
                            ImageUrl = "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=500&auto=format&fit=crop&q=60",
                            Name = "Churrasco Mixto",
                            Price = 8.50m,
                            RestaurantId = 1,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Jugo de fruta natural 500ml",
                            ImageUrl = "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&auto=format&fit=crop&q=60",
                            Name = "Jugo Natural",
                            Price = 2.00m,
                            RestaurantId = 1,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Pizza clásica de mozzarella y albahaca",
                            ImageUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&auto=format&fit=crop&q=60",
                            Name = "Pizza Margarita",
                            Price = 9.00m,
                            RestaurantId = 2,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Bebida gaseosa",
                            ImageUrl = "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=60",
                            Name = "Gaseosa 500ml",
                            Price = 1.50m,
                            RestaurantId = 2,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "8 piezas de roll california",
                            ImageUrl = "https://images.unsplash.com/photo-1553621042-f6e147245754?w=500&auto=format&fit=crop&q=60",
                            Name = "Sushi Roll California",
                            Price = 7.50m,
                            RestaurantId = 3,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Porción de cheesecake",
                            ImageUrl = "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&auto=format&fit=crop&q=60",
                            Name = "Cheesecake",
                            Price = 4.00m,
                            RestaurantId = 3,
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Carne, queso, lechuga y tomate",
                            ImageUrl = "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500&auto=format&fit=crop&q=60",
                            Name = "Hamburguesa Clásica",
                            Price = 6.50m,
                            RestaurantId = 4,
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Doble carne, tocino y salsa BBQ",
                            ImageUrl = "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500&auto=format&fit=crop&q=60",
                            Name = "Hamburguesa BBQ",
                            Price = 7.50m,
                            RestaurantId = 4,
                            Stock = 30
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Papas fritas con queso fundido",
                            ImageUrl = "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=60",
                            Name = "Papas con queso",
                            Price = 3.50m,
                            RestaurantId = 4,
                            Stock = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Malteada cremosa de chocolate",
                            ImageUrl = "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=500&auto=format&fit=crop&q=60",
                            Name = "Malteada de chocolate",
                            Price = 3.00m,
                            RestaurantId = 4,
                            Stock = 40
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Café negro filtrado",
                            ImageUrl = "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=500&auto=format&fit=crop&q=60",
                            Name = "Café Americano",
                            Price = 1.75m,
                            RestaurantId = 5,
                            Stock = 100
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Espresso con leche vaporizada",
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&auto=format&fit=crop&q=60",
                            Name = "Capuccino",
                            Price = 2.25m,
                            RestaurantId = 5,
                            Stock = 80
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Porción de torta húmeda de chocolate",
                            ImageUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=500&auto=format&fit=crop&q=60",
                            Name = "Torta de chocolate",
                            Price = 3.75m,
                            RestaurantId = 5,
                            Stock = 25
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Croissant de mantequilla horneado",
                            ImageUrl = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&auto=format&fit=crop&q=60",
                            Name = "Croissant",
                            Price = 2.00m,
                            RestaurantId = 5,
                            Stock = 35
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Jugo de naranja natural 400ml",
                            ImageUrl = "https://images.unsplash.com/photo-1560781290-7dc94c0f8f4f?w=500&auto=format&fit=crop&q=60",
                            Name = "Jugo de naranja",
                            Price = 2.00m,
                            RestaurantId = 5,
                            Stock = 50
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Description = "Ceviche fresco de camarón con limón",
                            ImageUrl = "https://images.unsplash.com/photo-1554998171-89445e31c52b?w=500&auto=format&fit=crop&q=60",
                            Name = "Ceviche de camarón",
                            Price = 9.50m,
                            RestaurantId = 6,
                            Stock = 25
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Arroz con mariscos mixtos",
                            ImageUrl = "https://images.unsplash.com/photo-1548369937-47519962c11a?w=500&auto=format&fit=crop&q=60",
                            Name = "Arroz marinero",
                            Price = 8.75m,
                            RestaurantId = 6,
                            Stock = 20
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Sopa de pescado con yuca y cebolla curtida",
                            ImageUrl = "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500&auto=format&fit=crop&q=60",
                            Name = "Encebollado",
                            Price = 6.00m,
                            RestaurantId = 6,
                            Stock = 30
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Limonada natural bien helada",
                            ImageUrl = "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=500&auto=format&fit=crop&q=60",
                            Name = "Limonada",
                            Price = 1.75m,
                            RestaurantId = 6,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("Nami.API.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Nami.API.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle 10 y 5",
                            Category = "Comida típica",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=60",
                            Latitude = -0.1953,
                            Longitude = -78.485399999999998,
                            Name = "La Parrilla Criolla",
                            Rating = 4.5999999999999996,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Av. Amazonas 234",
                            Category = "Pizzería",
                            ImageUrl = "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800&auto=format&fit=crop&q=60",
                            Latitude = -0.2082,
                            Longitude = -78.4923,
                            Name = "Pizza Nostra",
                            Rating = 4.2999999999999998,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Av. 6 de Diciembre 500",
                            Category = "Comida japonesa",
                            ImageUrl = "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&auto=format&fit=crop&q=60",
                            Latitude = -0.19980000000000001,
                            Longitude = -78.432699999999997,
                            Name = "Sushi Zen",
                            Rating = 4.7000000000000002,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Av. Amazonas y Naciones Unidas",
                            Category = "Comida rápida",
                            ImageUrl = "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800&auto=format&fit=crop&q=60",
                            Latitude = -0.17849999999999999,
                            Longitude = -78.484999999999999,
                            Name = "Hamburguesas El Fogón",
                            Rating = 4.4000000000000004,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "García Moreno N2-36, Centro Histórico",
                            Category = "Cafetería",
                            ImageUrl = "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=60",
                            Latitude = -0.22009999999999999,
                            Longitude = -78.5124,
                            Name = "Café del Centro",
                            Rating = 4.5999999999999996,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Av. González Suárez N27-142",
                            Category = "Mariscos",
                            ImageUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=60",
                            Latitude = -0.1963,
                            Longitude = -78.479500000000002,
                            Name = "Mariscos La Caleta",
                            Rating = 4.5,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Nami.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nami.API.Models.Administrator", b =>
                {
                    b.HasBaseType("Nami.API.Models.User");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Administrator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Av. Principal 100",
                            DateBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@delivery.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Ana",
                            Gender = 1,
                            LastName = "Torres",
                            PasswordHash = "$2a$11$qNYoYQeSotuFui857iiB1OuJt1QtqARggr8IYRKZYEVj.3eAiKCXG",
                            Phone = "0999999999",
                            Status = 0,
                            Branch = "Matriz Quito",
                            Rol = "SuperAdmin",
                            Salary = 1200m
                        });
                });

            modelBuilder.Entity("Nami.API.Models.Client", b =>
                {
                    b.HasBaseType("Nami.API.Models.User");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Client");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Address = "Calle Los Álamos 45",
                            DateBirth = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cliente1@delivery.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Carlos",
                            Gender = 0,
                            LastName = "Pérez",
                            PasswordHash = "$2a$11$hvX4IFoZ1UAZLzzBWcXAIOlJCy7Gk/BQqtC9j3s4Fk5PXIxfLTH02",
                            Phone = "0988888881",
                            Status = 0,
                            RegisterDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Av. Amazonas 210",
                            DateBirth = new DateTime(1998, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cliente2@delivery.com",
                            FailedLoginAttempts = 0,
                            FirstName = "María",
                            Gender = 1,
                            LastName = "López",
                            PasswordHash = "$2a$11$hvX4IFoZ1UAZLzzBWcXAIOlJCy7Gk/BQqtC9j3s4Fk5PXIxfLTH02",
                            Phone = "0988888882",
                            Status = 0,
                            RegisterDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Nami.API.Models.Delivery", b =>
                {
                    b.HasBaseType("Nami.API.Models.User");

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<string>("LicencePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Delivery");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Address = "Sector La Floresta",
                            DateBirth = new DateTime(1993, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "courier1@delivery.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Jorge",
                            Gender = 0,
                            LastName = "Ramírez",
                            PasswordHash = "$2a$11$8xLd3G.dMRqKGFsYHyaVp.HyA7sbThqUKlyV2aMTkGtKrP6hp1dGa",
                            Phone = "0977777771",
                            Status = 0,
                            Availability = true,
                            LicencePlate = "PBX-1234",
                            Rating = 4.5,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "Sector El Bosque",
                            DateBirth = new DateTime(1996, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "courier2@delivery.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Lucía",
                            Gender = 1,
                            LastName = "Fernández",
                            PasswordHash = "$2a$11$8xLd3G.dMRqKGFsYHyaVp.HyA7sbThqUKlyV2aMTkGtKrP6hp1dGa",
                            Phone = "0977777772",
                            Status = 0,
                            Availability = true,
                            LicencePlate = "PBX-5678",
                            Rating = 4.7999999999999998,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 9,
                            Address = "Sector Carcelén",
                            DateBirth = new DateTime(1994, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "courier3@delivery.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Diego",
                            Gender = 0,
                            LastName = "Salazar",
                            PasswordHash = "$2a$11$8xLd3G.dMRqKGFsYHyaVp.HyA7sbThqUKlyV2aMTkGtKrP6hp1dGa",
                            Phone = "0977777773",
                            Status = 0,
                            Availability = true,
                            LicencePlate = "PBX-9012",
                            Rating = 4.2000000000000002,
                            VehicleType = 2
                        });
                });

            modelBuilder.Entity("Nami.API.Models.Cart", b =>
                {
                    b.HasOne("Nami.API.Models.Client", "Client")
                        .WithOne("Cart")
                        .HasForeignKey("Nami.API.Models.Cart", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Nami.API.Models.CartItem", b =>
                {
                    b.HasOne("Nami.API.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nami.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Nami.API.Models.Notification", b =>
                {
                    b.HasOne("Nami.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nami.API.Models.Order", b =>
                {
                    b.HasOne("Nami.API.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nami.API.Models.Delivery", "Delivery")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nami.API.Models.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Delivery");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Nami.API.Models.OrderDetail", b =>
                {
                    b.HasOne("Nami.API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nami.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Nami.API.Models.Payment", b =>
                {
                    b.HasOne("Nami.API.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Nami.API.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Nami.API.Models.Product", b =>
                {
                    b.HasOne("Nami.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nami.API.Models.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Nami.API.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nami.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Nami.API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Nami.API.Models.Restaurant", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Nami.API.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Nami.API.Models.Client", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Nami.API.Models.Delivery", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
